### ISSUE TITLE
🐞 Audio, Video and some files are not received by webhook

### ISSUE THREAD

**Issue by abdxdev** [aldinokemal/go-whatsapp-web-multidevice#157]
### What happened?

When I receive one of the following, I get an error: `[Client ERROR] Event handler panicked while handling a *events.Message: runtime error: index out of range [0] with length 0`
- GIF as image
- Audio
- Video
- All files other than JSON, PDF, GIF, JPG and PNG as document

### Reproduction Steps

```bash
1. Connect webhook to the application
2. Login to your WhatsApp using application
3. Send yourself one of the following:
- GIF as image
- Audio
- Video
- All files other than JSON and PDF
```

### Relevant log output

```bash
2024-06-06 14:44:23 whatsapp_go-1  | 09:44:23.306 [Client ERROR] Event handler panicked while handling a *events.Message: runtime error: index out of range [0] with length 0
2024-06-06 14:44:23 whatsapp_go-1  | goroutine 16999 [running]:
2024-06-06 14:44:23 whatsapp_go-1  | runtime/debug.Stack()
2024-06-06 14:44:23 whatsapp_go-1  |    /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
2024-06-06 14:44:23 whatsapp_go-1  | go.mau.fi/whatsmeow.(*Client).dispatchEvent.func1()
2024-06-06 14:44:23 whatsapp_go-1  |    /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240523075404-7f13c31d2cb1/client.go:758 +0x7d
2024-06-06 14:44:23 whatsapp_go-1  | panic({0xe1c520?, 0xc000d90198?})
2024-06-06 14:44:23 whatsapp_go-1  |    /usr/local/go/src/runtime/panic.go:914 +0x21f
2024-06-06 14:44:23 whatsapp_go-1  | github.com/aldinokemal/go-whatsapp-web-multidevice/pkg/whatsapp.ExtractMedia({0xe914ff, 0xd}, {0xfdc720, 0xc000390140?})
2024-06-06 14:44:23 whatsapp_go-1  |    /whatsapp/pkg/whatsapp/whatsapp.go:462 +0x4c5
2024-06-06 14:44:23 whatsapp_go-1  | github.com/aldinokemal/go-whatsapp-web-multidevice/pkg/whatsapp.forwardToWebhook(0xc00115e000)
2024-06-06 14:44:23 whatsapp_go-1  |    /whatsapp/pkg/whatsapp/whatsapp.go:387 +0x1029
2024-06-06 14:44:23 whatsapp_go-1  | github.com/aldinokemal/go-whatsapp-web-multidevice/pkg/whatsapp.handler({0xd4d860?, 0xc00115e000?})
2024-06-06 14:44:23 whatsapp_go-1  |    /whatsapp/pkg/whatsapp/whatsapp.go:260 +0x19dd
2024-06-06 14:44:23 whatsapp_go-1  | go.mau.fi/whatsmeow.(*Client).dispatchEvent(0xc00115e000?, {0xd4d860?, 0xc00115e000})
2024-06-06 14:44:23 whatsapp_go-1  |    /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240523075404-7f13c31d2cb1/client.go:762 +0xd5
2024-06-06 14:44:23 whatsapp_go-1  | go.mau.fi/whatsmeow.(*Client).handleDecryptedMessage(0xc0001226c0?, 0xc00027c480, 0xc000296a00, 0x0)
2024-06-06 14:44:23 whatsapp_go-1  |    /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240523075404-7f13c31d2cb1/message.go:576 +0xe5
2024-06-06 14:44:23 whatsapp_go-1  | go.mau.fi/whatsmeow.(*Client).decryptMessages(0xc000490000, 0xc00027c480, 0xc0006663f0)
2024-06-06 14:44:23 whatsapp_go-1  |    /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240523075404-7f13c31d2cb1/message.go:231 +0xc25
2024-06-06 14:44:23 whatsapp_go-1  | go.mau.fi/whatsmeow.(*Client).handleEncryptedMessage(0xc000490000, 0xc0006663f0)
2024-06-06 14:44:23 whatsapp_go-1  |    /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240523075404-7f13c31d2cb1/message.go:51 +0x39a
2024-06-06 14:44:23 whatsapp_go-1  | go.mau.fi/whatsmeow.(*Client).handlerQueueLoop.func1()
2024-06-06 14:44:23 whatsapp_go-1  |    /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240523075404-7f13c31d2cb1/client.go:709 +0x83
2024-06-06 14:44:23 whatsapp_go-1  | created by go.mau.fi/whatsmeow.(*Client).handlerQueueLoop in goroutine 16004
2024-06-06 14:44:23 whatsapp_go-1  |    /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240523075404-7f13c31d2cb1/client.go:707 +0x195
```

### Application Version

4.14.0

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by aldinokemal** [comment]
- Sending Docx file
<img width="1177" alt="Xnip2024-06-22_21-43-11" src="https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/14232125/65dcdf28-30b3-4fcb-b6e7-b94b0f226210">

- Sending GIF
<img width="777" alt="Xnip2024-06-22_21-42-31" src="https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/14232125/204894c0-8b7e-403b-b760-eb6098c25c29">

- Sending Audio
<img width="1042" alt="Xnip2024-06-22_21-41-43" src="https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/14232125/b76ab3cc-8b2e-446a-8aec-e714956e8992">


seems working fine from my end @abdbbdii
