### ISSUE TITLE
Error when sending webhook with message text containing URL preview

### ISSUE THREAD

**Issue by Mosharush** [aldinokemal/go-whatsapp-web-multidevice#98]
# Description

While attempting to send a webhook with a message text that includes a URL preview, I encountered an error. Interestingly, when the same message is sent without the preview, it gets through successfully.

# Steps to Reproduce

1. Run the whatsapp-go project with webhook target param.
1. Login with QR Code with Whatsapp account.
1. Receive a message with a URL in the body and a preview on Whatsapp.
1. The error described below occurs, and the webhook is not actually received by the service intended to handle it.
- Note: Removing the preview before sending the message with the URL resolves the issue and the webhook is received as expected.

# Error Log

```
time="2023-10-26T10:41:19Z" level=info msg="Forwarding event to webhook:http://172.31.36.1:2000/income-message?instanceId=3"
10:41:19.006 [Client ERROR] Event handler panicked while handling a *events.Message: runtime error: invalid memory address or nil pointer dereference
goroutine 184 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
go.mau.fi/whatsmeow.(*Client).dispatchEvent.func1()
        /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20231006094259-c6eaf52f1357/client.go:631 +0x7d
panic({0xc7ac00?, 0x13bfc10?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/aldinokemal/go-whatsapp-web-multidevice/pkg/whatsapp.forwardToWebhook(0xc0001c0780)
        /whatsapp/pkg/whatsapp/whatsapp.go:298 +0x204
github.com/aldinokemal/go-whatsapp-web-multidevice/pkg/whatsapp.handler({0xc65480?, 0xc0001c0780?})
        /whatsapp/pkg/whatsapp/whatsapp.go:237 +0x18df
go.mau.fi/whatsmeow.(*Client).dispatchEvent(0xc000020000?, {0xc65480, 0xc0001c0780})
        /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20231006094259-c6eaf52f1357/client.go:635 +0xcd
go.mau.fi/whatsmeow.(*Client).handleDecryptedMessage(0xc000593d30?, 0xc000232100, 0xc000560900, 0x0)
        /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20231006094259-c6eaf52f1357/message.go:510 +0xc7
go.mau.fi/whatsmeow.(*Client).decryptMessages(0xc000020000, 0xc000232100, 0xc0005f8210)
        /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20231006094259-c6eaf52f1357/message.go:180 +0xb11
go.mau.fi/whatsmeow.(*Client).handleEncryptedMessage(0xc000020000, 0x4cd9af?)
        /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20231006094259-c6eaf52f1357/message.go:48 +0x325
go.mau.fi/whatsmeow.(*Client).handlerQueueLoop.func1()
        /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20231006094259-c6eaf52f1357/client.go:582 +0x83
created by go.mau.fi/whatsmeow.(*Client).handlerQueueLoop in goroutine 125
```

## Additional Context

    Library Version: go.mau.fi/whatsmeow@v0.0.0-20231006094259-c6eaf52f1357

**Comment by Mosharush** [comment]
Resolved!! Thanks @GalShnapp 
@aldinokemal the docker image will updated as well?

**Comment by aldinokemal** [comment]
yes docker will update soon
